package reads

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/halbritt/striatum/go/pkg/db"
	"github.com/halbritt/striatum/go/pkg/installers"
	"github.com/halbritt/striatum/go/pkg/laneproviderauth"
	"github.com/halbritt/striatum/go/pkg/rpc"
	"github.com/jackc/pgx/v5"
)

type doctorFakeRow struct{}

func (doctorFakeRow) Scan(dest ...any) error {
	return nil
}

type doctorFakeRunner struct {
	scalarQueries []string
}

func (r *doctorFakeRunner) Exec(_ context.Context, _ string, _ ...any) error {
	return nil
}

func (r *doctorFakeRunner) QueryRow(_ context.Context, _ string, _ ...any) db.Row {
	return doctorFakeRow{}
}

func (r *doctorFakeRunner) QueryScalar(_ context.Context, sql string, _ ...any) (string, error) {
	r.scalarQueries = append(r.scalarQueries, sql)
	if strings.Contains(sql, "substrate_version") {
		return "8", nil
	}
	return "", nil
}

func (r *doctorFakeRunner) BeginTx(_ context.Context) (db.TxRunner, error) {
	return nil, errors.New("not implemented")
}

func TestHandleDoctorReadsSubstrateVersionFromSchemaMetaKey(t *testing.T) {
	runner := &doctorFakeRunner{}

	result, err := HandleDoctor(context.Background(), runner, rpc.Envelope{Params: map[string]any{}})
	if err != nil {
		t.Fatalf("HandleDoctor: %v", err)
	}

	if result["schema_version"] != 8 {
		t.Fatalf("schema_version = %v, want 8", result["schema_version"])
	}
	if result["ok"] != true {
		t.Fatalf("ok = %v, want true; problems=%v", result["ok"], result["problems"])
	}
	readScope, ok := result["pg_read_scope"].(map[string]any)
	if !ok {
		t.Fatalf("doctor result missing pg_read_scope block: %#v", result["pg_read_scope"])
	}
	if readScope["posture"] != pgReadScopeBroadRuntimeSelect {
		t.Fatalf("pg_read_scope posture = %v, want %s", readScope["posture"], pgReadScopeBroadRuntimeSelect)
	}
	// substrate_version must be the FIRST scalar query doctor issues. (RFC 0107
	// added the daemon-global principals scope query, so the total scalar-query
	// count is no longer exactly one.)
	if len(runner.scalarQueries) == 0 || !strings.Contains(runner.scalarQueries[0], "substrate_version") {
		t.Fatalf("doctor did not read schema_meta substrate_version first: %#v", runner.scalarQueries)
	}
}

func TestDoctorSeparatesActionableWarningsFromAdvisoryNotices(t *testing.T) {
	warnings := []string{
		"artifact_legacy_unverifiable.art_1: legacy blob record predates blob storage",
		"barrier_debris_terminal_run.barrier_1: terminal canceled run has archived fan-in barrier debris",
		"codex_token_env_absent: STRIATUM_MCP_TOKEN is not set in the environment; runtime client-token exists",
		"worktree_debris_terminal_run.wt_1: terminal canceled run has archived worktree debris",
		"skills_outdated: project codex bundle was generated by an older runner",
	}
	records := []map[string]any{
		{"check": artifactLegacyUnverifiable, "id": "art_1"},
		{"check": "barrier_debris_terminal_run", "id": "barrier_1"},
		{"check": "worktree_debris_terminal_run", "id": "wt_1"},
	}

	actionable, actionableRecords, notices, noticeRecords := doctorSplitAdvisoryNotices(warnings, records)

	actionableJoined := strings.Join(actionable, "\n")
	for _, want := range []string{"worktree_debris_terminal_run.wt_1", "skills_outdated"} {
		if !strings.Contains(actionableJoined, want) {
			t.Fatalf("actionable warnings missing %q:\n%s", want, actionableJoined)
		}
	}
	if strings.Contains(actionableJoined, "artifact_legacy_unverifiable") || strings.Contains(actionableJoined, "barrier_debris_terminal_run") || strings.Contains(actionableJoined, "codex_token_env_absent") {
		t.Fatalf("advisory notices leaked into actionable warnings:\n%s", actionableJoined)
	}
	noticeJoined := strings.Join(notices, "\n")
	for _, want := range []string{"artifact_legacy_unverifiable.art_1", "barrier_debris_terminal_run.barrier_1", "codex_token_env_absent"} {
		if !strings.Contains(noticeJoined, want) {
			t.Fatalf("notices missing %q:\n%s", want, noticeJoined)
		}
	}
	if len(actionableRecords) != 1 || actionableRecords[0]["check"] != "worktree_debris_terminal_run" {
		t.Fatalf("actionableRecords = %#v, want only worktree_debris_terminal_run", actionableRecords)
	}
	if len(noticeRecords) != 2 {
		t.Fatalf("noticeRecords = %#v, want artifact + barrier notice records", noticeRecords)
	}
	availabilityOK, provenanceOK := doctorProblemPlaneSummary(nil, nil)
	if !availabilityOK || !provenanceOK {
		t.Fatalf("advisory notices should not affect problem planes: availability_ok=%v provenance_ok=%v", availabilityOK, provenanceOK)
	}
}

func TestDoctorProblemPlanesClassifyNonVerboseProblemStrings(t *testing.T) {
	availabilityOK, provenanceOK := doctorProblemPlaneSummary(
		[]string{"recovery_sweep_cursor_wedged.run_1: claimable_job_count=1"},
		nil,
	)
	if availabilityOK || !provenanceOK {
		t.Fatalf("availability problem planes = availability_ok=%v provenance_ok=%v", availabilityOK, provenanceOK)
	}

	availabilityOK, provenanceOK = doctorProblemPlaneSummary(
		[]string{"worktree_head_unreachable.wt_1: worktree HEAD abc is not reachable"},
		nil,
	)
	if !availabilityOK || provenanceOK {
		t.Fatalf("provenance problem planes = availability_ok=%v provenance_ok=%v", availabilityOK, provenanceOK)
	}
}

func TestHandleDoctorDoesNotRunProviderAuthByDefaultOrVerbose(t *testing.T) {
	orig := doctorLaneProviderAuthCheck
	t.Cleanup(func() { doctorLaneProviderAuthCheck = orig })
	doctorLaneProviderAuthCheck = func(context.Context, laneproviderauth.Params) laneproviderauth.Result {
		t.Fatal("ordinary doctor must not run provider auth preflight")
		return laneproviderauth.Result{}
	}

	for _, params := range []map[string]any{
		{},
		{"verbose": true},
	} {
		if _, err := HandleDoctor(context.Background(), &doctorFakeRunner{}, rpc.Envelope{Params: params}); err != nil {
			t.Fatalf("HandleDoctor(%#v): %v", params, err)
		}
	}
}

func TestHandleDoctorLaneProviderAuthOptInShape(t *testing.T) {
	orig := doctorLaneProviderAuthCheck
	t.Cleanup(func() { doctorLaneProviderAuthCheck = orig })
	t.Setenv("STRIATUM_MCP_TOKEN", "must-not-leak")
	t.Setenv("DATABASE_URL", "postgres://must-not-leak")
	var captured laneproviderauth.Params
	doctorLaneProviderAuthCheck = func(_ context.Context, params laneproviderauth.Params) laneproviderauth.Result {
		captured = params
		if params.Timeout != 12*time.Second {
			t.Fatalf("timeout = %v, want 12s", params.Timeout)
		}
		renderedEnv := strings.Join(params.Env, "\n")
		if strings.Contains(renderedEnv, "STRIATUM_MCP_TOKEN") || strings.Contains(renderedEnv, "DATABASE_URL") || strings.Contains(renderedEnv, "must-not-leak") {
			t.Fatalf("provider auth env leaked secret material: %s", renderedEnv)
		}
		return laneproviderauth.Result{
			Checked:           true,
			Provider:          laneproviderauth.ProviderCodex,
			RunID:             params.RunID,
			LaneID:            params.LaneID,
			Status:            laneproviderauth.StatusPassed,
			RawOutputReturned: false,
			Network:           "provider_cli_may_use_network",
			Costing:           "provider_tokens_may_be_spent",
			DurationMS:        7,
			Remediation:       "none",
		}
	}

	result, err := HandleDoctor(context.Background(), &doctorFakeRunner{}, rpc.Envelope{Params: map[string]any{
		"lane_provider_auth": "codex",
		"run_id":             "run_1",
		"lane_id":            "author",
		"timeout":            "12s",
	}})
	if err != nil {
		t.Fatalf("HandleDoctor lane-provider-auth: %v", err)
	}
	if captured.Provider != laneproviderauth.ProviderCodex || captured.RunID != "run_1" || captured.LaneID != "author" {
		t.Fatalf("captured params = %#v", captured)
	}
	if result["checked"] != true || result["provider"] != "codex" || result["status"] != laneproviderauth.StatusPassed || result["raw_output_returned"] != false {
		t.Fatalf("opt-in result = %#v", result)
	}
	if result["failure_class"] != nil {
		t.Fatalf("passed result failure_class = %#v", result["failure_class"])
	}
}

func TestHandleDoctorLaneProviderAuthAcceptsProviderAwareValues(t *testing.T) {
	orig := doctorLaneProviderAuthCheck
	t.Cleanup(func() { doctorLaneProviderAuthCheck = orig })

	t.Run("claude", func(t *testing.T) {
		var captured laneproviderauth.Params
		doctorLaneProviderAuthCheck = func(_ context.Context, params laneproviderauth.Params) laneproviderauth.Result {
			captured = params
			return laneproviderauth.Result{
				Checked:           true,
				Provider:          params.Provider,
				Status:            laneproviderauth.StatusPassed,
				Probe:             laneproviderauth.ProbeClaudeOfflineExpiry,
				RawOutputReturned: false,
				Network:           "no_network_offline_credential_file",
				Costing:           "no_provider_tokens_spent",
				Remediation:       "none",
			}
		}

		result, err := HandleDoctor(context.Background(), &doctorFakeRunner{}, rpc.Envelope{Params: map[string]any{
			"lane_provider_auth": "claude",
		}})
		if err != nil {
			t.Fatalf("HandleDoctor claude lane-provider-auth: %v", err)
		}
		if captured.Provider != laneproviderauth.ProviderClaude {
			t.Fatalf("captured provider = %q, want claude", captured.Provider)
		}
		if result["checked"] != true || result["provider"] != laneproviderauth.ProviderClaude || result["probe"] != laneproviderauth.ProbeClaudeOfflineExpiry {
			t.Fatalf("claude opt-in result = %#v", result)
		}
	})

	t.Run("unsupported", func(t *testing.T) {
		doctorLaneProviderAuthCheck = func(_ context.Context, params laneproviderauth.Params) laneproviderauth.Result {
			return laneproviderauth.Result{
				Checked:           false,
				Provider:          params.Provider,
				Status:            laneproviderauth.StatusFailed,
				FailureClass:      laneproviderauth.FailureUnsupported,
				RawOutputReturned: false,
				Network:           "provider_cli_may_use_network",
				Costing:           "provider_tokens_may_be_spent",
				Remediation:       "configure a provider with a supported auth preflight",
			}
		}

		result, err := HandleDoctor(context.Background(), &doctorFakeRunner{}, rpc.Envelope{Params: map[string]any{
			"lane_provider_auth": "agy",
		}})
		if err != nil {
			t.Fatalf("HandleDoctor unsupported lane-provider-auth: %v", err)
		}
		if result["provider"] != "agy" || result["status"] != laneproviderauth.StatusFailed || result["failure_class"] != laneproviderauth.FailureUnsupported {
			t.Fatalf("unsupported provider result = %#v", result)
		}
		if strings.TrimSpace(result["remediation"].(string)) == "" {
			t.Fatalf("unsupported provider result lacks remediation: %#v", result)
		}
	})
}

func TestHandleDoctorLaneProviderAuthRunAsUsesLaneHome(t *testing.T) {
	origCheck := doctorLaneProviderAuthCheck
	origCurrentUser := currentUsername
	origLookupHome := lookupOSUserHome
	t.Cleanup(func() {
		doctorLaneProviderAuthCheck = origCheck
		currentUsername = origCurrentUser
		lookupOSUserHome = origLookupHome
	})
	currentUsername = func() string { return "daemon-user" }
	lookupOSUserHome = func(name string) (string, bool) {
		if name == "striatum-lane" {
			return "/home/striatum-lane", true
		}
		return "", false
	}
	t.Setenv(laneOSUserEnv, "striatum-lane")
	t.Setenv("CODEX_HOME", "/home/operator/.codex")
	t.Setenv("XDG_CONFIG_HOME", "/home/operator/.config")
	t.Setenv("XDG_CACHE_HOME", "/home/operator/.cache")
	var captured laneproviderauth.Params
	doctorLaneProviderAuthCheck = func(_ context.Context, params laneproviderauth.Params) laneproviderauth.Result {
		captured = params
		return laneproviderauth.Result{
			Checked:           true,
			Provider:          laneproviderauth.ProviderCodex,
			Status:            laneproviderauth.StatusPassed,
			RawOutputReturned: false,
			Network:           "provider_cli_may_use_network",
			Costing:           "provider_tokens_may_be_spent",
			Remediation:       "none",
		}
	}

	if _, err := HandleDoctor(context.Background(), &doctorFakeRunner{}, rpc.Envelope{Params: map[string]any{
		"lane_provider_auth": "codex",
	}}); err != nil {
		t.Fatalf("HandleDoctor lane-provider-auth: %v", err)
	}
	if captured.RunAsUser != "striatum-lane" {
		t.Fatalf("RunAsUser = %q, want striatum-lane", captured.RunAsUser)
	}
	values := doctorEnvValues(captured.Env)
	if values["HOME"] != "/home/striatum-lane" {
		t.Fatalf("HOME = %q, want lane user home", values["HOME"])
	}
	for _, forbidden := range []string{"CODEX_HOME", "XDG_CONFIG_HOME", "XDG_CACHE_HOME"} {
		if _, ok := values[forbidden]; ok {
			t.Fatalf("doctor provider auth env inherited operator %s: %#v", forbidden, values)
		}
	}
	if authHome := laneproviderauth.ResolveAuthHome(laneproviderauth.ProviderCodex, captured.Env); authHome != "/home/striatum-lane/.codex" {
		t.Fatalf("auth home = %q, want lane HOME/.codex", authHome)
	}
}

func doctorEnvValues(env []string) map[string]string {
	values := map[string]string{}
	for _, entry := range env {
		key, value, ok := strings.Cut(entry, "=")
		if ok {
			values[key] = value
		}
	}
	return values
}

type doctorSkillsFakeRunner struct {
	doctorFakeRunner
	repoRoot string
}

func (r *doctorSkillsFakeRunner) Query(_ context.Context, sql string, _ ...any) (pgx.Rows, error) {
	switch {
	case strings.Contains(sql, "FROM striatumd.repositories"):
		return dashboardAllRowsFromMaps([]map[string]any{{"repo_root": r.repoRoot}}), nil
	case strings.Contains(sql, "COUNT(*) AS c"):
		return dashboardAllRowsFromMaps([]map[string]any{{"c": int64(0)}}), nil
	default:
		return dashboardAllRowsFromMaps(nil), nil
	}
}

func TestHandleDoctorWarnsOnStaleGeneratedSkills(t *testing.T) {
	home := t.TempDir()
	target := t.TempDir()
	t.Setenv("HOME", home)
	if _, err := installers.InstallSkills(installers.SkillsParams{
		Target: target, Home: home, Profile: "claude_code", Scope: "project", Namespace: "striatum-", Version: "2.8.0",
	}); err != nil {
		t.Fatal(err)
	}

	oldVersion := packageStriatumVersion
	packageStriatumVersion = "2.24.0"
	defer func() { packageStriatumVersion = oldVersion }()

	result, err := HandleDoctor(context.Background(), &doctorSkillsFakeRunner{repoRoot: target}, rpc.Envelope{
		Params: map[string]any{"repository_id": "repo_1"},
	})
	if err != nil {
		t.Fatalf("HandleDoctor: %v", err)
	}
	skills, ok := result["skills"].(map[string]any)
	if !ok || skills["checked"] != true {
		t.Fatalf("skills doctor block = %#v", result["skills"])
	}
	warnings := strings.Join(result["warnings"].([]string), "\n")
	for _, want := range []string{"skills_outdated", "2.8.0", "2.24.0", "skills install"} {
		if !strings.Contains(warnings, want) {
			t.Fatalf("warnings missing %q:\n%s", want, warnings)
		}
	}
	if _, err := os.Stat(filepath.Join(target, ".claude", "skills", "striatum-workflow", "SKILL.md")); err != nil {
		t.Fatalf("stale skill should remain for doctor-only warning: %v", err)
	}
}

type doctorWorktreeAnchorFakeRunner struct {
	doctorFakeRunner
	rows []map[string]any
}

func (r *doctorWorktreeAnchorFakeRunner) Query(_ context.Context, sql string, _ ...any) (pgx.Rows, error) {
	switch {
	case strings.Contains(sql, "FROM striatumd.job_worktrees"):
		return dashboardAllRowsFromMaps(r.rows), nil
	case strings.Contains(sql, "COUNT(*) AS c"):
		return dashboardAllRowsFromMaps([]map[string]any{{"c": int64(0)}}), nil
	default:
		return dashboardAllRowsFromMaps(nil), nil
	}
}

func TestDoctorFlagsUnreachableWorktreeHead(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skipf("git not on PATH: %v", err)
	}
	repoRoot := t.TempDir()
	baseSHA := readsGitInit(t, repoRoot)
	runID := "run_doctor_anchor"
	jobID := "job_doctor_anchor"
	worktreeID := "wt_doctor_anchor"
	runBranch := "wf/doctor-anchor"
	worktreeRel := filepath.ToSlash(filepath.Join(".striatum", "worktrees", worktreeID))
	worktreeRoot := filepath.Join(repoRoot, filepath.FromSlash(worktreeRel))

	readsGitRun(t, repoRoot, "branch", runBranch, baseSHA)
	readsGitRun(t, repoRoot, "worktree", "add", "--detach", worktreeRoot, runBranch)
	if err := os.WriteFile(filepath.Join(worktreeRoot, "worktree.txt"), []byte("worktree\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	readsGitRun(t, worktreeRoot, "add", "worktree.txt")
	readsGitRun(t, worktreeRoot, "commit", "-q", "-m", "worktree change")
	worktreeHead := readsGitRevParse(t, worktreeRoot, "HEAD")

	runner := &doctorWorktreeAnchorFakeRunner{rows: []map[string]any{{
		"worktree_id":     worktreeID,
		"run_id":          runID,
		"job_id":          jobID,
		"lease_id":        "lease_doctor_anchor",
		"base_branch":     runBranch,
		"branch_name":     runBranch,
		"repo_root":       repoRoot,
		"worktree_path":   worktreeRel,
		"state":           "active",
		"workflow_job_id": "author_draft",
		"job_state":       "completed",
	}}}

	result, err := HandleDoctor(context.Background(), runner, rpc.Envelope{
		Params: map[string]any{"repository_id": "repo_doctor_anchor", "verbose": true},
	})
	if err != nil {
		t.Fatalf("HandleDoctor: %v", err)
	}
	if result["ok"] == true {
		t.Fatalf("doctor ok = true, want false")
	}
	if result["availability_ok"] != true {
		t.Fatalf("availability_ok = %v, want true", result["availability_ok"])
	}
	if result["provenance_ok"] == true {
		t.Fatalf("provenance_ok = true, want false")
	}
	problems := strings.Join(result["problems"].([]string), "\n")
	for _, want := range []string{"worktree_head_unreachable." + worktreeID, "job_completed_without_anchor." + jobID, worktreeHead} {
		if !strings.Contains(problems, want) {
			t.Fatalf("doctor problems missing %q:\n%s", want, problems)
		}
	}
	records := result["problem_records"].([]map[string]any)
	checks := map[string]bool{}
	for _, record := range records {
		checks[stringFrom(record, "check")] = true
		if plane := record["plane"]; plane != doctorProblemPlaneProvenance {
			t.Fatalf("problem record %s plane = %v, want %s", stringFrom(record, "check"), plane, doctorProblemPlaneProvenance)
		}
	}
	if !checks["worktree_head_unreachable"] || !checks["job_completed_without_anchor"] {
		t.Fatalf("problem_records = %#v", records)
	}
}

// TestDoctorWarnsFanInSiblingUnintegrated is the #290 doctor reachability
// invariant: in a still-running run, a completed repo-write job whose worktree
// HEAD is reachable only via a refs/striatum pin (NOT from the run branch) is a
// stranded fan-in author. Doctor surfaces it as a WARNING (ok stays true — it
// must not re-red the green baseline or fire on historical/terminal runs).
func TestDoctorWarnsFanInSiblingUnintegrated(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skipf("git not on PATH: %v", err)
	}
	repoRoot := t.TempDir()
	baseSHA := readsGitInit(t, repoRoot)
	runID := "run_doctor_fanin"
	jobID := "job_doctor_fanin"
	worktreeID := "wt_doctor_fanin"
	runBranch := "wf/doctor-fanin"
	worktreeRel := filepath.ToSlash(filepath.Join(".striatum", "worktrees", worktreeID))
	worktreeRoot := filepath.Join(repoRoot, filepath.FromSlash(worktreeRel))

	// Worktree HEAD diverges from the run branch (a sibling advanced it) and is
	// preserved ONLY under a refs/striatum pin — never integrated into the run branch.
	readsGitRun(t, repoRoot, "branch", runBranch, baseSHA)
	readsGitRun(t, repoRoot, "worktree", "add", "--detach", worktreeRoot, baseSHA)
	if err := os.WriteFile(filepath.Join(worktreeRoot, "worktree.txt"), []byte("worktree\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	readsGitRun(t, worktreeRoot, "add", "worktree.txt")
	readsGitRun(t, worktreeRoot, "commit", "-q", "-m", "worktree change")
	worktreeHead := readsGitRevParse(t, worktreeRoot, "HEAD")
	// Advance the run branch to a disjoint sibling commit so the worktree HEAD is
	// NOT on the run branch.
	if err := os.WriteFile(filepath.Join(repoRoot, "mainline.txt"), []byte("mainline\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	readsGitRun(t, repoRoot, "add", "mainline.txt")
	readsGitRun(t, repoRoot, "commit", "-q", "-m", "sibling run branch change")
	readsGitRun(t, repoRoot, "update-ref", "refs/heads/"+runBranch, readsGitRevParse(t, repoRoot, "HEAD"))
	// Pin the worktree HEAD (reachable via pin, not the run branch).
	readsGitRun(t, repoRoot, "update-ref", "refs/striatum/"+runID+"/"+jobID+"/1", worktreeHead)

	runner := &doctorWorktreeAnchorFakeRunner{rows: []map[string]any{{
		"worktree_id":     worktreeID,
		"run_id":          runID,
		"job_id":          jobID,
		"lease_id":        "lease_doctor_fanin",
		"base_branch":     runBranch,
		"branch_name":     runBranch,
		"repo_root":       repoRoot,
		"worktree_path":   worktreeRel,
		"state":           "active",
		"workflow_job_id": "author_draft",
		"job_state":       "completed",
		"run_state":       "running",
	}}}

	result, err := HandleDoctor(context.Background(), runner, rpc.Envelope{
		Params: map[string]any{"repository_id": "repo_doctor_fanin", "verbose": true},
	})
	if err != nil {
		t.Fatalf("HandleDoctor: %v", err)
	}
	// Warning only — must NOT red ok.
	if result["ok"] != true {
		t.Fatalf("doctor ok = %v, want true (fan-in stranding is a warning, not a problem):\nproblems=%v", result["ok"], result["problems"])
	}
	warnings := strings.Join(result["warnings"].([]string), "\n")
	if !strings.Contains(warnings, "fanin_sibling_unintegrated."+worktreeID) || !strings.Contains(warnings, worktreeHead) {
		t.Fatalf("warnings missing fanin_sibling_unintegrated for %s:\n%s", worktreeID, warnings)
	}
}
